<?php


namespace Database\Seeders;

use App\Models\SmartjabarOpd;
use Illuminate\Database\Seeder;

class SmartjabarOpdSeeder extends Seeder
{
    public function run(): void
    {
        $opds = [
            "DINAS KOMUNIKASI DAN INFORMATIKA",
            "DINAS PEMUDA DAN OLAHRAGA",
            "DINAS LINGKUNGAN HIDUP",
            "DINAS TENAGA KERJA DAN TRANSMIGRASI",
            "DINAS KOPERASI DAN USAHA KECIL",
            "BADAN PENGHUBUNG",
            "DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL",
            "INSPEKTORAT DAERAH",
            "SEKRETARIAT DPRD",
            "DINAS PEMBERDAYAAN PEREMPUAN, PERLINDUNGAN ANAK DAN KELUARGA BERENCANA",
            "DINAS KELAUTAN DAN PERIKANAN",
            "DINAS PEMBERDAYAAN MASYARAKAT DAN DESA",
            "DINAS KEHUTANAN",
            "DINAS PERINDUSTRIAN DAN PERDAGANGAN",
            "DINAS SOSIAL",
            "DINAS SUMBER DAYA AIR",
            "DINAS ENERGI DAN SUMBER DAYA MINERAL",
            "DINAS PERHUBUNGAN",
            "DINAS TANAMAN PANGAN DAN HORTIKULTURA",
            "DINAS KETAHANAN PANGAN DAN PETERNAKAN",
            "DINAS BINA MARGA DAN PENATAAN RUANG",
            "DINAS PERUMAHAN DAN PERMUKIMAN",
            "BADAN KEPEGAWAIAN DAERAH",
            "DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU",
            "SEKRETARIAT DAERAH",
            "BADAN PENGEMBANGAN SUMBER DAYA MANUSIA",
            "DINAS PARIWISATA DAN KEBUDAYAAN",
            "BADAN PENANGGULANGAN BENCANA DAERAH",
            "DINAS PERKEBUNAN",
            "DINAS PENDIDIKAN",
            "BADAN PENGELOLAAN KEUANGAN DAN ASET DAERAH",
            "DINAS PERPUSTAKAAN DAN KEARSIPAN DAERAH",
            "SATUAN POLISI PAMONG PRAJA",
            "DINAS KESEHATAN",
            "BADAN PENELITIAN DAN PENGEMBANGAN DAERAH",
            "BADAN PERENCANAAN PEMBANGUNAN DAERAH",
            "BADAN PENDAPATAN DAERAH",
            "BADAN KESATUAN BANGSA DAN POLITIK"
        ];

        foreach ($opds as $opd) {
            SmartjabarOpd::firstOrCreate(['name' => $opd]);
        }
    }
}
